### ISSUE TITLE
contributors:  main page

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#36]
This screen had been stubbed out in the 2017 CI software, but is to be implemented in 2018. This screen will look very much like the home screen, except whereas that screen presents a list of articles, this screen will present a list of contributors. The contributor “Unknown” is to be excluded from this list.
The listed information will be the same as the information now displayed with the hover feature on the home screen: name, identifier, life dates, education, nationality, gender, and comment. Some of these fields are null for some contributors. The list will be ordered using ALLCAPS(contributors.full_name).

**Comment by saracarl** [comment]
Current display entry will look like this:

 Campbell, Thomas 07/27/1777 - 06/15/1844
M Scottish University of Glasgow

Born in Glasgow; prominent poet and editor; The Pleasures of Hope (1799); editor of New Monthly Magazine and Metropolitan Magazine; advocate for Polish independence. See ODNB.

Questions:
M/F or should we spell out "Male" and "Female"
How do you want "M Scottish University of Glasgow" separated?  Semicolons like so:
"M; Scottish; University of Glasgow" or periods:
"M. Scottish. University of Glasgow" or something else?

@gsimons1946

**Comment by gsimons1946** [comment]
Let's spell out "Male" and "Female."
 
Let's use semicolons to separate fields.

Should we make an entry continuous, so that after life dates we have a semicolon and then go to gender, and then after education we go to the comment?

Please remember that sometimes some of these fields will be null, and we don't want multiple semicolons in a row.

I'm concerned about how multiple entries on the screen will look, and how easily it will be for a viewer to distinguish one contributor from the next. Perhaps the names should be boldfaced to mark the start of each entry.

Gary

    On Monday, April 23, 2018, 1:25:45 PM EDT, Sara Brumfield <notifications@github.com> wrote:  
 
 
Current display entry will look like this:

Campbell, Thomas 07/27/1777 - 06/15/1844
M Scottish University of Glasgow

Born in Glasgow; prominent poet and editor; The Pleasures of Hope (1799); editor of New Monthly Magazine and Metropolitan Magazine; advocate for Polish independence. See ODNB.

Questions:
M/F or should we spell out "Male" and "Female"
How do you want "M Scottish University of Glasgow" separated? Semicolons like so:
"M; Scottish; University of Glasgow" or periods:
"M. Scottish. University of Glasgow" or something else?

@gsimons1946

**Comment by benwbrum** [comment]
To display: `identifier` disambiguates names, and is sometimes  life dates, sometimes a common pseudonym.  These are displayed on the contributor filter list correctly.
